version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: prozapas_db
    environment:
      POSTGRES_USER: prozapas_user
      POSTGRES_PASSWORD: zapas_zapas
      POSTGRES_DB: prozapas_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: