"""initial schema

Revision ID: 9627621bfdfd
Revises: 
Create Date: 2026-08-07 08:26:24.523416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9627621bfdfd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Последовательности номеров заказов. Отдельно стоящие SEQUENCE автоген не
    # видит, поэтому это единственная ручная вставка в файле. Номер выдаёт
    # сервер: при двух рабочих местах клиенты выдали бы одинаковые.
    op.execute("CREATE SEQUENCE IF NOT EXISTS order_number_ours_seq START 2001")
    op.execute("CREATE SEQUENCE IF NOT EXISTS order_number_theirs_seq START 3001")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_item',
    sa.Column('article', sa.Text(), nullable=False),
    sa.Column('code1c', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('unit_weight', sa.Numeric(precision=10, scale=3), server_default='0', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', name || ' ' || article || ' ' || coalesce(code1c, ''))", persisted=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('unit_weight >= 0', name=op.f('ck_catalog_item_unit_weight')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_item')),
    sa.UniqueConstraint('article', name=op.f('uq_catalog_item_article')),
    sa.UniqueConstraint('code1c', name=op.f('uq_catalog_item_code1c'))
    )
    op.create_index('ix_catalog_item_active', 'catalog_item', ['id'], unique=False, postgresql_where=sa.text('is_archived IS false'))
    op.create_index('ix_catalog_item_search', 'catalog_item', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('idempotency_key',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotency_key'))
    )
    op.create_index('ix_idempotency_key_created', 'idempotency_key', ['created_at'], unique=False)
    op.create_table('login_attempt',
    sa.Column('ip_address', sa.Text(), nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempt'))
    )
    op.create_index('ix_login_attempt_ip', 'login_attempt', ['ip_address', 'created_at'], unique=False)
    op.create_table('role',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('code', name=op.f('uq_role_code'))
    )
    op.create_table('supplier',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('inn', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier')),
    sa.UniqueConstraint('name', name=op.f('uq_supplier_name'))
    )
    op.create_table('warehouse',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('responsible_user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_own', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['user_account.id'], name=op.f('fk_warehouse_responsible_user_id'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse')),
    sa.UniqueConstraint('code', name=op.f('uq_warehouse_code')),
    sa.UniqueConstraint('name', name=op.f('uq_warehouse_name'))
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('can_view', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_edit', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("section IN ('orders', 'shipping', 'receiving', 'catalog', 'stock', 'users')", name=op.f('ck_role_permission_section')),
    sa.CheckConstraint('can_view OR NOT can_edit', name=op.f('ck_role_permission_edit_needs_view')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_permission_role_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'section', name=op.f('pk_role_permission'))
    )
    op.create_table('stock_balance',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('reserved', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('min_qty >= 0', name=op.f('ck_stock_balance_min_qty')),
    sa.CheckConstraint('qty >= 0', name=op.f('ck_stock_balance_qty')),
    sa.CheckConstraint('reserved <= qty', name=op.f('ck_stock_balance_reserved_le_qty')),
    sa.CheckConstraint('reserved >= 0', name=op.f('ck_stock_balance_reserved')),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_item.id'], name=op.f('fk_stock_balance_item_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_stock_balance_warehouse_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('item_id', 'warehouse_id', name=op.f('pk_stock_balance'))
    )
    op.create_index('ix_stock_balance_below_min', 'stock_balance', ['item_id'], unique=False, postgresql_where=sa.text('qty - reserved < min_qty'))
    op.create_index('ix_stock_balance_warehouse', 'stock_balance', ['warehouse_id'], unique=False)
    op.create_table('user_account',
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'blocked')", name=op.f('ck_user_account_status')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_account_role_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_user_account_warehouse_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account'))
    )
    op.create_index('ix_user_account_email', 'user_account', [sa.text('lower(email)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_user_account_login', 'user_account', [sa.text('lower(login)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_user_account_role', 'user_account', ['role_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('entity', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_audit_log_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity', 'entity_id', 'created_at'], unique=False)
    op.create_index('ix_audit_log_user', 'audit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('order',
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='created', nullable=False),
    sa.Column('counterparty_warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('responsible_user_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint("direction IN ('ours', 'theirs')", name=op.f('ck_order_direction')),
    sa.CheckConstraint("status IN ('created', 'processing', 'shipped', 'received', 'declined', 'cancelled')", name=op.f('ck_order_status')),
    sa.ForeignKeyConstraint(['counterparty_warehouse_id'], ['warehouse.id'], name=op.f('fk_order_counterparty_warehouse_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['user_account.id'], name=op.f('fk_order_responsible_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order')),
    sa.UniqueConstraint('number', name=op.f('uq_order_number'))
    )
    op.create_index('ix_order_list', 'order', ['direction', 'status', 'created_at'], unique=False)
    op.create_index('ix_order_number_prefix', 'order', ['number'], unique=False, postgresql_ops={'number': 'text_pattern_ops'})
    op.create_index('ix_order_warehouse', 'order', ['counterparty_warehouse_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_refresh_token_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_token_token_hash'))
    )
    op.create_index('ix_refresh_token_active', 'refresh_token', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('ix_refresh_token_user', 'refresh_token', ['user_id'], unique=False)
    op.create_table('stock_movement',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('delta', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=True),
    sa.Column('doc_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("type IN ('receipt', 'shipment', 'writeoff', 'recount', 'reserve', 'unreserve')", name=op.f('ck_stock_movement_type')),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_item.id'], name=op.f('fk_stock_movement_item_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_stock_movement_user_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_stock_movement_warehouse_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movement'))
    )
    op.create_index('ix_stock_movement_doc', 'stock_movement', ['doc_type', 'doc_id'], unique=False)
    op.create_index('ix_stock_movement_item', 'stock_movement', ['item_id', 'created_at'], unique=False)
    op.create_index('ix_stock_movement_warehouse', 'stock_movement', ['warehouse_id', 'created_at'], unique=False)
    op.create_table('order_position',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint('qty > 0', name=op.f('ck_order_position_qty')),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_item.id'], name=op.f('fk_order_position_item_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_order_position_order_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_position')),
    sa.UniqueConstraint('order_id', 'item_id', name=op.f('uq_order_position_order_id_item_id'))
    )
    op.create_table('order_status_event',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("status IN ('created', 'processing', 'shipped', 'received', 'declined', 'cancelled')", name=op.f('ck_order_status_event_status')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_order_status_event_order_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_order_status_event_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_event'))
    )
    op.create_index('ix_order_status_event_order', 'order_status_event', ['order_id', 'occurred_at'], unique=False)
    op.create_table('receipt_batch',
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), server_default='waiting', nullable=False),
    sa.Column('responsible_user_id', sa.BigInteger(), nullable=True),
    sa.Column('ship_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint("status IN ('waiting', 'progress', 'done')", name=op.f('ck_receipt_batch_status')),
    sa.CheckConstraint('supplier_id IS NOT NULL OR order_id IS NOT NULL', name=op.f('ck_receipt_batch_supplier_or_order')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_receipt_batch_order_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['user_account.id'], name=op.f('fk_receipt_batch_responsible_user_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_receipt_batch_supplier_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_receipt_batch_warehouse_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipt_batch')),
    sa.UniqueConstraint('number', name=op.f('uq_receipt_batch_number'))
    )
    op.create_index('ix_receipt_batch_list', 'receipt_batch', ['status', 'created_at'], unique=False)
    op.create_table('shipment',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), server_default='waiting', nullable=False),
    sa.Column('responsible_user_id', sa.BigInteger(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint("status IN ('waiting', 'progress', 'done')", name=op.f('ck_shipment_status')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_shipment_order_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['user_account.id'], name=op.f('fk_shipment_responsible_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment')),
    sa.UniqueConstraint('order_id', name=op.f('uq_shipment_order_id'))
    )
    op.create_index('ix_shipment_list', 'shipment', ['status', 'created_at'], unique=False)
    op.create_table('receipt_batch_position',
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('boxes', sa.Integer(), nullable=False),
    sa.Column('box_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('accepted_boxes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('missing_boxes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('actual_weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint('accepted_boxes >= 0', name=op.f('ck_receipt_batch_position_accepted_boxes')),
    sa.CheckConstraint('box_weight > 0', name=op.f('ck_receipt_batch_position_box_weight')),
    sa.CheckConstraint('boxes > 0', name=op.f('ck_receipt_batch_position_boxes')),
    sa.CheckConstraint('missing_boxes >= 0', name=op.f('ck_receipt_batch_position_missing_boxes')),
    sa.ForeignKeyConstraint(['batch_id'], ['receipt_batch.id'], name=op.f('fk_receipt_batch_position_batch_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_item.id'], name=op.f('fk_receipt_batch_position_item_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipt_batch_position')),
    sa.UniqueConstraint('batch_id', 'item_id', name=op.f('uq_receipt_batch_position_batch_id_item_id'))
    )
    op.create_table('receipt_scan',
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('actual_weight', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('is_missing', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['receipt_batch.id'], name=op.f('fk_receipt_scan_batch_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_item.id'], name=op.f('fk_receipt_scan_item_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_receipt_scan_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipt_scan')),
    sa.UniqueConstraint('batch_id', 'barcode', name=op.f('uq_receipt_scan_batch_id_barcode'))
    )
    op.create_table('shipment_box',
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('barcode', sa.Text(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint('qty > 0', name=op.f('ck_shipment_box_qty')),
    sa.CheckConstraint('weight > 0', name=op.f('ck_shipment_box_weight')),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_item.id'], name=op.f('fk_shipment_box_item_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], name=op.f('fk_shipment_box_shipment_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_shipment_box_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_box')),
    sa.UniqueConstraint('barcode', name=op.f('uq_shipment_box_barcode'))
    )
    op.create_index('ix_shipment_box_item', 'shipment_box', ['item_id'], unique=False)
    op.create_index('ix_shipment_box_shipment', 'shipment_box', ['shipment_id'], unique=False)
    # ### end Alembic commands ###

    # Связь warehouse ↔ user_account циклическая: ответственный за склад — это
    # пользователь, а у пользователя есть склад. Автоген создаёт колонку, но
    # ключ ставить не берётся — вешаем его, когда обе таблицы уже есть.
    op.create_foreign_key(
        'fk_warehouse_responsible_user_id', 'warehouse', 'user_account',
        ['responsible_user_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    """Downgrade schema."""
    # Циклический ключ снимаем первым, иначе user_account не удалить:
    # на него ещё ссылается warehouse.
    op.drop_constraint('fk_warehouse_responsible_user_id', 'warehouse',
                       type_='foreignkey')

    op.execute("DROP SEQUENCE IF EXISTS order_number_theirs_seq")
    op.execute("DROP SEQUENCE IF EXISTS order_number_ours_seq")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shipment_box_shipment', table_name='shipment_box')
    op.drop_index('ix_shipment_box_item', table_name='shipment_box')
    op.drop_table('shipment_box')
    op.drop_table('receipt_scan')
    op.drop_table('receipt_batch_position')
    op.drop_index('ix_shipment_list', table_name='shipment')
    op.drop_table('shipment')
    op.drop_index('ix_receipt_batch_list', table_name='receipt_batch')
    op.drop_table('receipt_batch')
    op.drop_index('ix_order_status_event_order', table_name='order_status_event')
    op.drop_table('order_status_event')
    op.drop_table('order_position')
    op.drop_index('ix_stock_movement_warehouse', table_name='stock_movement')
    op.drop_index('ix_stock_movement_item', table_name='stock_movement')
    op.drop_index('ix_stock_movement_doc', table_name='stock_movement')
    op.drop_table('stock_movement')
    op.drop_index('ix_refresh_token_user', table_name='refresh_token')
    op.drop_index('ix_refresh_token_active', table_name='refresh_token', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('refresh_token')
    op.drop_index('ix_order_warehouse', table_name='order')
    op.drop_index('ix_order_number_prefix', table_name='order', postgresql_ops={'number': 'text_pattern_ops'})
    op.drop_index('ix_order_list', table_name='order')
    op.drop_table('order')
    op.drop_index('ix_audit_log_user', table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_user_account_role', table_name='user_account')
    op.drop_index('ix_user_account_login', table_name='user_account', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_user_account_email', table_name='user_account', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('user_account')
    op.drop_index('ix_stock_balance_warehouse', table_name='stock_balance')
    op.drop_index('ix_stock_balance_below_min', table_name='stock_balance', postgresql_where=sa.text('qty - reserved < min_qty'))
    op.drop_table('stock_balance')
    op.drop_table('role_permission')
    op.drop_table('warehouse')
    op.drop_table('supplier')
    op.drop_table('role')
    op.drop_index('ix_login_attempt_ip', table_name='login_attempt')
    op.drop_table('login_attempt')
    op.drop_index('ix_idempotency_key_created', table_name='idempotency_key')
    op.drop_table('idempotency_key')
    op.drop_index('ix_catalog_item_search', table_name='catalog_item', postgresql_using='gin')
    op.drop_index('ix_catalog_item_active', table_name='catalog_item', postgresql_where=sa.text('is_archived IS false'))
    op.drop_table('catalog_item')
    # ### end Alembic commands ###
